minimumReleaseAgeExclude:
  - '@lexical/a11y@0.47.0'
  - '@lexical/clipboard@0.47.0'
  - '@lexical/code-core@0.47.0'
  - '@lexical/code-shiki@0.47.0'
  - '@lexical/devtools-core@0.47.0'
  - '@lexical/dragon@0.47.0'
  - '@lexical/extension@0.47.0'
  - '@lexical/hashtag@0.47.0'
  - '@lexical/history@0.47.0'
  - '@lexical/html@0.47.0'
  - '@lexical/internal@0.47.0'
  - '@lexical/link@0.47.0'
  - '@lexical/list@0.47.0'
  - '@lexical/mark@0.47.0'
  - '@lexical/markdown@0.47.0'
  - '@lexical/overflow@0.47.0'
  - '@lexical/plain-text@0.47.0'
  - '@lexical/react@0.47.0'
  - '@lexical/rich-text@0.47.0'
  - '@lexical/selection@0.47.0'
  - '@lexical/table@0.47.0'
  - '@lexical/text@0.47.0'
  - '@lexical/utils@0.47.0'
  - '@lexical/yjs@0.47.0'
  - '@lottiefiles/dotlottie-react@0.19.9'
  - '@lottiefiles/dotlottie-web@0.77.1'
  - i18next@26.3.6
  - lexical@0.47.0
  - lucide-react@1.24.0
  - react-i18next@17.0.9
